# Generated by Django 6.0.6 on 2026-06-30 09:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cats', '0002_initial'),
        ('shelters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FosterProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('max_capacity', models.PositiveIntegerField()),
                ('current_capacity', models.PositiveIntegerField(default=0)),
                ('preferred_ages', models.JSONField(default=list)),
                ('can_handle_medical', models.BooleanField(default=False)),
                ('can_handle_kittens', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('address', models.CharField(max_length=500)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shelter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shelters.shelter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'foster_profiles',
            },
        ),
        migrations.CreateModel(
            name='FosterPlacement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('expected_return_at', models.DateField(blank=True, null=True)),
                ('actual_return_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('ONGOING', 'Ongoing'), ('RETURNED', 'Returned'), ('ADOPTED_FROM_FOSTER', 'Adopted from Foster'), ('CAT_DECEASED', 'Cat Deceased')], default='ONGOING', max_length=30)),
                ('check_in_notes', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.cat')),
                ('placed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelters.shelter')),
                ('foster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foster.fosterprofile')),
            ],
            options={
                'db_table': 'foster_placements',
            },
        ),
    ]
