# Generated by Django 6.0.6 on 2026-07-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('SHELTER_ADMIN', 'Shelter Admin'), ('VET', 'Vet'), ('VOLUNTEER', 'Volunteer'), ('CAT_OWNER', 'Cat Owner'), ('ADOPTER', 'Adopter'), ('GUEST', 'Guest')], default='ADOPTER', max_length=20),
        ),
    ]
