# Generated by Django 6.0.6 on 2026-07-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_date_of_birth_adopterprofile_vetprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
