# Generated by Django 6.0.6 on 2026-07-06 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_last_activity_at'),
        ('shelters', '0003_dischargerecord_recipient_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vetprofile',
            name='clinic_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vetprofile',
            name='clinic_registration_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vetprofile',
            name='practice_type',
            field=models.CharField(choices=[('CLINIC', 'Clinic'), ('SHELTER', 'Shelter')], default='CLINIC', max_length=10),
        ),
        migrations.AddField(
            model_name='vetprofile',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='vetprofile',
            name='shelter_admin_decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vetprofile',
            name='shelter_admin_decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vet_shelter_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vetprofile',
            name='shelter_admin_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='vetprofile',
            name='specializations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='vetprofile',
            name='super_admin_decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vetprofile',
            name='super_admin_decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vet_super_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vetprofile',
            name='super_admin_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='vetprofile',
            name='target_shelter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vet_applications', to='shelters.shelter'),
        ),
        migrations.AlterField(
            model_name='vetprofile',
            name='specialization',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
