# Generated by Django 6.0.6 on 2026-07-06 06:54

import apps.accounts.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_vetprofile_clinic_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedVetRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_number', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('reason', models.CharField(choices=[('SUSPENDED', 'Suspended after final rejection'), ('FLAGGED', 'Flagged after lapsed appeal window')], max_length=20)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'blacklisted_vet_registrations',
            },
        ),
        migrations.AddField(
            model_name='vetprofile',
            name='appeal_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vetprofile',
            name='appeals_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vetprofile',
            name='blocked_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='vetprofile',
            name='lifecycle_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected (appeal open)'), ('APPEAL_UNDER_REVIEW', 'Appeal under review'), ('SUPER_FINAL_REVIEW', 'Super admin final review'), ('SUSPENDED', 'Suspended'), ('FLAGGED', 'Flagged')], default='PENDING', max_length=24),
        ),
        migrations.AddField(
            model_name='vetprofile',
            name='requires_shelter_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vetprofile',
            name='shelter_admin_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='vetprofile',
            name='super_admin_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='vetprofile',
            name='shelter_admin_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('NOT_REQUIRED', 'Not required')], default='PENDING', max_length=12),
        ),
        migrations.AlterField(
            model_name='vetprofile',
            name='super_admin_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('NOT_REQUIRED', 'Not required')], default='PENDING', max_length=12),
        ),
        migrations.CreateModel(
            name='VetAppeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('explanation', models.TextField()),
                ('document', models.FileField(upload_to=apps.accounts.models.vet_appeal_document_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('needs_super_review', models.BooleanField(default=False)),
                ('needs_shelter_review', models.BooleanField(default=False)),
                ('super_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('NOT_REQUIRED', 'Not required')], default='NOT_REQUIRED', max_length=12)),
                ('super_decided_at', models.DateTimeField(blank=True, null=True)),
                ('super_reject_details', models.TextField(blank=True)),
                ('super_reject_anomalies', models.TextField(blank=True)),
                ('shelter_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('NOT_REQUIRED', 'Not required')], default='NOT_REQUIRED', max_length=12)),
                ('shelter_decided_at', models.DateTimeField(blank=True, null=True)),
                ('shelter_reject_details', models.TextField(blank=True)),
                ('shelter_reject_anomalies', models.TextField(blank=True)),
                ('super_final_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('NOT_REQUIRED', 'Not required')], default='NOT_REQUIRED', max_length=12)),
                ('super_final_decided_at', models.DateTimeField(blank=True, null=True)),
                ('super_final_details', models.TextField(blank=True)),
                ('super_final_anomalies', models.TextField(blank=True)),
                ('shelter_decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vet_appeal_shelter_decisions', to=settings.AUTH_USER_MODEL)),
                ('super_decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vet_appeal_super_decisions', to=settings.AUTH_USER_MODEL)),
                ('super_final_decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vet_appeal_final_decisions', to=settings.AUTH_USER_MODEL)),
                ('vet_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='accounts.vetprofile')),
            ],
            options={
                'db_table': 'vet_appeals',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
