export const mockAuditLogs = [
  { id: 'log-1', actor_name: 'Sam Rivera', actor_email: 'sam.rivera@shelteros.mock', actor_role: 'SUPER_ADMIN', action: 'CREATE', entity_type: 'Shelter', entity_id: 'shelter-2', new_value: { message: 'Shelter onboarded to the platform' }, ip_address: '10.0.0.4', performed_at: '2026-09-08T10:00:00Z' },
  { id: 'log-2', actor_name: 'Jordan Blake', actor_email: 'jordan.blake@shelteros.mock', actor_role: 'SHELTER_ADMIN', action: 'UPDATE', entity_type: 'Pet', entity_id: 'pet-1', new_value: { message: 'Status changed from FOSTERED to IN_SHELTER' }, ip_address: '10.0.0.7', performed_at: '2026-09-07T15:30:00Z' },
  { id: 'log-3', actor_name: 'Amina Hassan', actor_email: 'amina.hassan@shelteros.mock', actor_role: 'SHELTER_ADMIN', action: 'CREATE', entity_type: 'Donation', entity_id: 'don-3', new_value: { message: 'Recorded donation of Rs. 5,000' }, ip_address: '10.0.0.9', performed_at: '2026-09-05T09:00:00Z' },
  { id: 'log-4', actor_name: 'Sam Rivera', actor_email: 'sam.rivera@shelteros.mock', actor_role: 'SUPER_ADMIN', action: 'DELETE', entity_type: 'User', entity_id: 'u-10', new_value: { message: 'Account deactivated per user request' }, ip_address: '10.0.0.4', performed_at: '2026-08-30T13:00:00Z' },
  { id: 'log-5', actor_name: 'Jordan Blake', actor_email: 'jordan.blake@shelteros.mock', actor_role: 'SHELTER_ADMIN', action: 'CREATE', entity_type: 'Shelter', entity_id: 'shelter-1', new_value: { message: 'Shelter profile created' }, ip_address: '10.0.0.7', performed_at: '2026-08-01T08:00:00Z' },
  { id: 'log-6', actor_name: 'Casey Nguyen', actor_email: 'casey.nguyen@shelteros.mock', actor_role: 'EMPLOYEE', action: 'LOGIN', entity_type: null, entity_id: null, new_value: null, ip_address: '10.0.0.21', performed_at: '2026-09-11T08:05:00Z' },
  { id: 'log-7', actor_name: 'Sam Rivera', actor_email: 'sam.rivera@shelteros.mock', actor_role: 'SUPER_ADMIN', action: 'CAMPAIGN_COMPLETED', entity_type: 'Campaign', entity_id: 'camp-1', new_value: { message: 'Winter Shelter Fund reached its target' }, ip_address: '10.0.0.4', performed_at: '2026-07-20T12:00:00Z' },
  { id: 'log-8', actor_name: 'Priya Singh', actor_email: 'priya.singh@shelteros.mock', actor_role: 'EMPLOYEE', action: 'LOGOUT', entity_type: null, entity_id: null, new_value: null, ip_address: '10.0.0.22', performed_at: '2026-07-18T17:40:00Z' },
];
