"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-dummy-development-key-12345')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework', 
    'corsheaders',

     # Third-party packages
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'drf_spectacular',
    'django_filters',

    # Your 18 apps
    'apps.core',
    'apps.accounts',
    'apps.cats',
    'apps.shelters',
    'apps.volunteers',
    'apps.rescue',
    'apps.lost_found',
    'apps.adoption',
    'apps.medical',
    'apps.wellness',
    'apps.foster',
    'apps.inventory',
    'apps.finance',
    'apps.notifications',
    'apps.messaging',
    'apps.analytics',
    'apps.maps',
    'apps.audit',
]

AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@pawtrack.com')
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:5173')

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME':     os.getenv('DB_NAME'),
        'USER':     os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST':     os.getenv('DB_HOST', 'localhost'),
        'PORT':     os.getenv('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# ── CORS ──────────────────────────────────────────
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:3000",
    "http://localhost:8081",
]

# ── Django REST Framework ─────────────────────────
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'apps.core.authentication.JWTAuthenticationWithBlacklist',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# ── JWT Settings ──────────────────────────────────
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME':  timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS':  True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS512',
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# ── Spectacular (Swagger) ─────────────────────────
SPECTACULAR_SETTINGS = {
    'TITLE': 'PawTrack OS API',
    'DESCRIPTION': 'Cat welfare management platform',
    'VERSION': '1.0.0',
}

# ── Celery Configurations ─────────────────────────
CELERY_BROKER_URL        = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND    = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT    = ['json']
CELERY_TASK_SERIALIZER   = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_ALWAYS_EAGER = DEBUG


# The backend that performs the *actual* delivery (SMTP in prod, console in
# dev by default). Configurable via the EMAIL_BACKEND env var.
EMAIL_DELIVERY_BACKEND = os.getenv('EMAIL_BACKEND')
if not EMAIL_DELIVERY_BACKEND:
    if DEBUG:
        EMAIL_DELIVERY_BACKEND   = 'django.core.mail.backends.console.EmailBackend'
    else:
        EMAIL_DELIVERY_BACKEND   = 'django.core.mail.backends.smtp.EmailBackend'

# All mail goes through the threaded wrapper so form submissions never block on
# SMTP. It hands delivery to EMAIL_DELIVERY_BACKEND in a background daemon
# thread and returns immediately. This keeps requests fast both locally (where
# Celery runs eagerly in-request) and in production.
EMAIL_BACKEND            = 'apps.core.email_backend.ThreadedEmailBackend'
EMAIL_HOST               = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT               = 587
EMAIL_USE_TLS            = True
EMAIL_HOST_USER          = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD      = os.getenv('EMAIL_HOST_PASSWORD', '')

# Celery Beat Schedule
from celery.schedules import crontab
CELERY_BEAT_SCHEDULE = {
    'run-matching-engine': {
        'task': 'apps.lost_found.tasks.run_matching_engine',
        'schedule': 300.0,  # every 5 minutes
    },
    'vaccination-due-reminders': {
        'task': 'apps.wellness.tasks.send_vaccination_reminders',
        'schedule': crontab(hour=8, minute=0),
    },
    'medication-dose-reminders': {
        'task': 'apps.wellness.tasks.send_medication_reminders',
        'schedule': crontab(hour=7, minute=0),
    },
    'close-expired-campaigns': {
        'task': 'apps.finance.tasks.close_expired_campaigns',
        'schedule': crontab(hour=0, minute=0),
    },
    'foster-checkin-reminders': {
        'task': 'apps.foster.tasks.send_checkin_reminders',
        'schedule': crontab(hour=10, minute=0, day_of_week=1),
    },
    'appointment-reminders': {
        'task': 'apps.wellness.tasks.send_appointment_reminders',
        'schedule': crontab(minute=0),  # every hour
    },
}
