# Generated by Django 6.0.6 on 2026-07-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='payment_reference',
            field=models.TextField(blank=True),
        ),
    ]
