# Generated by Django 6.0.6 on 2026-06-30 09:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('registration_number', models.CharField(max_length=100, unique=True)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(default='Pakistan', max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('capacity_total', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('logo_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_shelter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shelters',
            },
        ),
        migrations.CreateModel(
            name='IntakeRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('intake_date', models.DateTimeField(auto_now_add=True)),
                ('intake_source', models.CharField(choices=[('RESCUE', 'Rescue'), ('SURRENDER', 'Surrender'), ('TRANSFER', 'Transfer'), ('STRAY_FOUND', 'Stray Found'), ('BORN_IN_SHELTER', 'Born in Shelter')], max_length=30)),
                ('initial_health_status', models.CharField(choices=[('HEALTHY', 'Healthy'), ('SICK', 'Sick'), ('INJURED', 'Injured'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('quarantine_required', models.BooleanField(default=False)),
                ('quarantine_until', models.DateField(blank=True, null=True)),
                ('housing_assignment', models.CharField(blank=True, max_length=200)),
                ('intake_notes', models.TextField(blank=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intake_records', to='cats.cat')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelters.shelter')),
            ],
            options={
                'db_table': 'intake_records',
            },
        ),
        migrations.CreateModel(
            name='DischargeRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discharge_date', models.DateTimeField(auto_now_add=True)),
                ('discharge_type', models.CharField(choices=[('ADOPTED', 'Adopted'), ('TRANSFERRED', 'Transferred'), ('FOSTERED', 'Fostered'), ('EUTHANIZED', 'Euthanized'), ('RETURNED_TO_OWNER', 'Returned to Owner'), ('DECEASED', 'Deceased')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.cat')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('destination_shelter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transfers', to='shelters.shelter')),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelters.shelter')),
            ],
            options={
                'db_table': 'discharge_records',
            },
        ),
        migrations.CreateModel(
            name='ShelterStaff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_in_shelter', models.CharField(blank=True, max_length=50)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='shelters.shelter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shelter_staff',
                'unique_together': {('shelter', 'user')},
            },
        ),
    ]
