# Generated by Django 6.0.6 on 2026-07-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dischargerecord',
            name='discharge_type',
            field=models.CharField(choices=[('ADOPTED', 'Adopted'), ('TRANSFERRED', 'Transferred'), ('FOSTERED', 'Fostered'), ('EUTHANIZED', 'Euthanized'), ('RETURNED_TO_OWNER', 'Returned to Owner'), ('DECEASED', 'Deceased'), ('ESCAPED', 'Escaped'), ('OTHER', 'Other')], max_length=30),
        ),
    ]
