# Generated by Django 6.0.6 on 2026-07-05 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0002_alter_dischargerecord_discharge_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dischargerecord',
            name='recipient_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='dischargerecord',
            name='recipient_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='intakerecord',
            name='surrenderer_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='intakerecord',
            name='surrenderer_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
