import api from './axiosConfig';
export const adoptionApi = {
  browse:            (params)     => api.get('/adoption/browse/', { params }),
  getDetail:         (catId)      => api.get(`/adoption/browse/${catId}/`),
  createListing:     (data)       => api.post('/adoption/listings/', data),
  updateListing:     (id, data)   => api.put(`/adoption/listings/${id}/`, data),
  deleteListing:     (id)         => api.delete(`/adoption/listings/${id}/`),
  getFavorites:      ()           => api.get('/adoption/favorites/'),
  addFavorite:       (catId)      => api.post(`/adoption/favorites/${catId}/`),
  removeFavorite:    (catId)      => api.delete(`/adoption/favorites/${catId}/`),
  submitApplication: (data)       => api.post('/adoption/applications/', data),
  myApplications:    (params)     => api.get('/adoption/applications/me/', { params }),
  listApplications:  (params)     => api.get('/adoption/applications/', { params }),
  getApplication:    (id)         => api.get(`/adoption/applications/${id}/`),
  moveToReview:      (id)         => api.put(`/adoption/applications/${id}/review/`),
  scheduleInterview: (id, data)   => api.post(`/adoption/applications/${id}/interview/`, data),
  recordOutcome:     (id, data)   => api.put(`/adoption/interviews/${id}/outcome/`, data),
  approve:           (id)         => api.post(`/adoption/applications/${id}/approve/`),
  reject:            (id, reason) => api.post(`/adoption/applications/${id}/reject/`, { rejection_reason: reason }),
  allApplications:   (params)     => api.get('/adoption/applications/', { params }),
  review:            (id, data)   => api.put(`/adoption/applications/${id}/review/`, data),
  withdraw:          (id)         => api.post(`/adoption/applications/${id}/withdraw/`),
};
