import api from './axiosConfig';
export const medicalApi = {
  listRecords:         (catId, p)    => api.get(`/medical/cats/${catId}/records/`, { params: p }),
  createRecord:        (catId, data) => api.post(`/medical/cats/${catId}/records/`, data),
  getRecord:           (id)          => api.get(`/medical/records/${id}/`),
  updateRecord:        (id, data)    => api.put(`/medical/records/${id}/`, data),
  uploadAttachment:    (id, fd)      => api.post(`/medical/records/${id}/attachments/`, fd,
                                          { headers: { 'Content-Type': 'multipart/form-data' } }),
  listAllergies:       (catId)       => api.get(`/medical/cats/${catId}/allergies/`),
  addAllergy:          (catId, data) => api.post(`/medical/cats/${catId}/allergies/`, data),
  updateAllergy:       (id, data)    => api.put(`/medical/allergies/${id}/`, data),
  listVaccinations:    (catId)       => api.get(`/vaccinations/cats/${catId}/`),
  upcoming:            (catId)       => api.get(`/vaccinations/cats/${catId}/upcoming/`),
  addVaccination:      (catId, data) => api.post(`/vaccinations/cats/${catId}/`, data),
  updateVaccination:   (id, data)    => api.put(`/vaccinations/${id}/`, data),
  deleteVaccination:   (id)          => api.delete(`/vaccinations/${id}/`),
  listPrescriptions:   (catId, p)    => api.get(`/medications/cats/${catId}/prescriptions/`, { params: p }),
  addPrescription:     (catId, data) => api.post(`/medications/cats/${catId}/prescriptions/`, data),
  updatePrescription:  (id, data)    => api.put(`/medications/prescriptions/${id}/`, data),
  completePrescription:(id)          => api.post(`/medications/prescriptions/${id}/complete/`),
  logDose:             (id, data)    => api.post(`/medications/prescriptions/${id}/dose-log/`, data),
  getDoseLogs:         (id)          => api.get(`/medications/prescriptions/${id}/dose-log/`),
  // Aliases used by pages
  listMedications:     (catId, p)    => api.get(`/medications/cats/${catId}/prescriptions/`, { params: p }),
  addMedication:       (data)        => api.post(`/medications/cats/${data.cat}/prescriptions/`, data),
  addRecord:           (catId, data) => api.post(`/medical/cats/${catId}/records/`, data),
};
