import api from './axiosConfig';
export const wellnessApi = {
  logWeight:        (catId, data)  => api.post(`/growth/cats/${catId}/weight/`, data),
  weightHistory:    (catId, p)     => api.get(`/growth/cats/${catId}/weight/`, { params: p }),
  weightChart:      (catId, period)=> api.get(`/growth/cats/${catId}/weight/chart/`, { params: { period } }),
  setNutrition:     (catId, data)  => api.post(`/growth/cats/${catId}/nutrition/`, data),
  getNutrition:     (catId)        => api.get(`/growth/cats/${catId}/nutrition/`),
  logFeeding:       (catId, data)  => api.post(`/growth/cats/${catId}/feeding/`, data),
  listAppointments: (params)       => api.get('/appointments/', { params }),
  myAppointments:   (params)       => api.get('/appointments/me/', { params }),
  catAppointments:  (catId, p)     => api.get(`/appointments/cats/${catId}/`, { params: p }),
  createAppointment:(data)         => api.post('/appointments/', data),
  confirm:          (id)           => api.put(`/appointments/${id}/confirm/`),
  complete:         (id, data)     => api.put(`/appointments/${id}/complete/`, data),
  cancel:           (id, reason)   => api.put(`/appointments/${id}/cancel/`, { cancellation_reason: reason }),
  reschedule:       (id, data)     => api.put(`/appointments/${id}/`, data),
  vetSchedule:      (date)         => api.get('/appointments/vet/schedule/', { params: { date } }),
  catAlerts:        (catId, p)     => api.get(`/health-alerts/cats/${catId}/`, { params: p }),
  myAlerts:         ()             => api.get('/health-alerts/me/'),
  vetAlerts:        (params)       => api.get('/health-alerts/vet/', { params }),
  shelterAlerts:    (shelterId)    => api.get(`/health-alerts/shelter/${shelterId}/`),
  resolve:          (id)           => api.put(`/health-alerts/${id}/resolve/`),
  // Aliases used by pages
  listWeightLogs:   (catId, p)     => api.get(`/growth/cats/${catId}/weight/`, { params: p }),
  listHealthAlerts: (params)       => api.get('/health-alerts/me/', { params }),
  vetHealthAlerts:  (params)       => api.get('/health-alerts/vet/', { params }),
  resolveHealthAlert:(id)          => api.put(`/health-alerts/${id}/resolve/`),
};
