# Generated by Django 6.0.6 on 2026-06-30 09:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shelters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('FOOD', 'Food'), ('MEDICINE', 'Medicine'), ('EQUIPMENT', 'Equipment'), ('CLEANING', 'Cleaning'), ('BEDDING', 'Bedding'), ('OTHER', 'Other')], max_length=20)),
                ('unit', models.CharField(max_length=50)),
                ('current_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('minimum_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('supplier_info', models.TextField(blank=True)),
                ('last_restocked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='shelters.shelter')),
            ],
            options={
                'db_table': 'inventory_items',
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('IN', 'In'), ('OUT', 'Out'), ('ADJUSTMENT', 'Adjustment')], max_length=15)),
                ('quantity_change', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_after', models.DecimalField(decimal_places=2, max_digits=10)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.inventoryitem')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inventory_transactions',
            },
        ),
    ]
