# Generated by Django 6.0.6 on 2026-07-02 10:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_found', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundcatreport',
            name='found_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
