# Generated by Django 6.0.6 on 2026-07-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_found', '0002_alter_foundcatreport_found_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundcatreport',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='foundcatreport',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
