# Generated by Django 6.0.6 on 2026-07-04 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_cat_adoption_fee_cat_adoption_requirements'),
        ('lost_found', '0003_foundcatreport_contact_email_and_more'),
        ('shelters', '0002_alter_dischargerecord_discharge_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundcatreport',
            name='resolved_cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='found_reports', to='cats.cat'),
        ),
        migrations.AddField(
            model_name='foundcatreport',
            name='shelter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='found_intakes', to='shelters.shelter'),
        ),
        migrations.AlterField(
            model_name='foundcatreport',
            name='found_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foundcatreport',
            name='found_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foundcatreport',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('MATCHED', 'Matched'), ('REUNITED', 'Reunited'), ('SHELTERED', 'Sheltered'), ('CLOSED', 'Closed')], default='OPEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='lostcatalert',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lostcatalert',
            name='last_seen_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lostcatalert',
            name='last_seen_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
