# Generated by Django 6.0.6 on 2026-07-03 19:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0002_alter_dischargerecord_discharge_type'),
        ('volunteers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShelterChangeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('reason', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_shelter_change_requests', to=settings.AUTH_USER_MODEL)),
                ('from_shelter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_change_requests', to='shelters.shelter')),
                ('to_shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_change_requests', to='shelters.shelter')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelter_change_requests', to='volunteers.volunteerprofile')),
            ],
            options={
                'db_table': 'shelter_change_requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
