# Generated by Django 6.0.6 on 2026-06-30 09:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='cats/')),
                ('photo_url', models.URLField(blank=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'cat_photos',
            },
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('age_years', models.PositiveIntegerField(default=0)),
                ('age_months', models.PositiveIntegerField(default=0)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('pattern', models.CharField(blank=True, max_length=100)),
                ('is_microchipped', models.BooleanField(default=False)),
                ('microchip_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('current_status', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('IN_SHELTER', 'In Shelter'), ('FOSTERED', 'Fostered'), ('ADOPTED', 'Adopted'), ('LOST', 'Lost'), ('DECEASED', 'Deceased')], default='UNKNOWN', max_length=20)),
                ('intake_date', models.DateField(blank=True, null=True)),
                ('is_neutered', models.BooleanField(default=False)),
                ('is_vaccinated_core', models.BooleanField(default=False)),
                ('primary_photo_url', models.URLField(blank=True)),
                ('behavioral_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('breed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cats', to='core.lookupvalue')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cats', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_cats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cats',
            },
        ),
    ]
