# Generated by Django 6.0.6 on 2026-07-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='adoption_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cat',
            name='adoption_requirements',
            field=models.TextField(blank=True),
        ),
    ]
