# Generated by Django 6.0.6 on 2026-06-30 09:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allergen', models.CharField(max_length=200)),
                ('reaction_description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('MILD', 'Mild'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe')], max_length=10)),
                ('discovered_at', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='cats.cat')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'allergies',
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_type', models.CharField(choices=[('DIAGNOSIS', 'Diagnosis'), ('SURGERY', 'Surgery'), ('INJURY', 'Injury'), ('ALLERGY', 'Allergy'), ('CHRONIC', 'Chronic'), ('TREATMENT', 'Treatment')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('occurred_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('attachments', models.JSONField(default=list)),
                ('is_ongoing', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='cats.cat')),
                ('vet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'medical_records',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('drug_name', models.CharField(max_length=200)),
                ('dosage_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('dosage_unit', models.CharField(max_length=50)),
                ('frequency', models.CharField(choices=[('ONCE_DAILY', 'Once Daily'), ('TWICE_DAILY', 'Twice Daily'), ('THREE_TIMES_DAILY', 'Three Times Daily'), ('EVERY_OTHER_DAY', 'Every Other Day'), ('AS_NEEDED', 'As Needed')], max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_ongoing', models.BooleanField(default=False)),
                ('instructions', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='cats.cat')),
                ('prescribed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prescriptions',
            },
        ),
        migrations.CreateModel(
            name='DoseLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('given_at', models.DateTimeField(auto_now_add=True)),
                ('was_given', models.BooleanField()),
                ('notes', models.TextField(blank=True)),
                ('missed_reason', models.CharField(blank=True, max_length=500)),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dose_logs', to='medical.prescription')),
            ],
            options={
                'db_table': 'dose_logs',
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vaccine_name', models.CharField(max_length=200)),
                ('vaccine_type', models.CharField(choices=[('CORE', 'Core'), ('NON_CORE', 'Non-Core')], max_length=20)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('administered_at', models.DateTimeField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('clinic_name', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('administered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='cats.cat')),
            ],
            options={
                'db_table': 'vaccinations',
            },
        ),
    ]
