# Generated by Django 6.0.6 on 2026-07-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='clinic_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='diagnosis',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='is_confidential',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='next_appointment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='treatment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='vet_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='occurred_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='record_type',
            field=models.CharField(choices=[('CHECKUP', 'Checkup'), ('VACCINATION', 'Vaccination'), ('ILLNESS', 'Illness'), ('INJURY', 'Injury'), ('SURGERY', 'Surgery'), ('DENTAL', 'Dental'), ('DIAGNOSTIC', 'Diagnostic'), ('DIAGNOSIS', 'Diagnosis'), ('TREATMENT', 'Treatment'), ('EMERGENCY', 'Emergency'), ('FOLLOW_UP', 'Follow-up'), ('ALLERGY', 'Allergy'), ('CHRONIC', 'Chronic'), ('OTHER', 'Other')], default='CHECKUP', max_length=20),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
