# Generated by Django 6.0.6 on 2026-06-30 09:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdopterFavorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'adopter_favorites',
            },
        ),
        migrations.CreateModel(
            name='AdoptionApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('INTERVIEW_SCHEDULED', 'Interview Scheduled'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='SUBMITTED', max_length=30)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'adoption_applications',
            },
        ),
        migrations.CreateModel(
            name='AdoptionInterview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('outcome', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('PENDING', 'Pending')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'adoption_interviews',
            },
        ),
        migrations.CreateModel(
            name='AdoptionListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('adoption_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'adoption_listings',
            },
        ),
        migrations.CreateModel(
            name='AdoptionQuestionnaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('living_type', models.CharField(choices=[('HOUSE_WITH_GARDEN', 'House with Garden'), ('APARTMENT', 'Apartment'), ('HOUSE_NO_GARDEN', 'House without Garden'), ('OTHER', 'Other')], max_length=30)),
                ('has_garden', models.BooleanField(default=False)),
                ('other_pets', models.BooleanField(default=False)),
                ('children_in_house', models.BooleanField(default=False)),
                ('work_hours_away', models.PositiveIntegerField()),
                ('previous_pet_experience', models.TextField()),
                ('financial_readiness_confirmed', models.BooleanField(default=False)),
                ('references', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'adoption_questionnaires',
            },
        ),
        migrations.CreateModel(
            name='AdoptionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('adoption_date', models.DateTimeField(auto_now_add=True)),
                ('adoption_fee_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'adoption_records',
            },
        ),
    ]
