# Generated by Django 6.0.6 on 2026-06-30 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adoption', '0001_initial'),
        ('cats', '0001_initial'),
        ('shelters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adopterfavorite',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.cat'),
        ),
        migrations.AddField(
            model_name='adopterfavorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.cat'),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='shelter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelters.shelter'),
        ),
        migrations.AddField(
            model_name='adoptioninterview',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='adoption.adoptionapplication'),
        ),
        migrations.AddField(
            model_name='adoptioninterview',
            name='conducted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adoptionlisting',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='cats.cat'),
        ),
        migrations.AddField(
            model_name='adoptionlisting',
            name='shelter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelters.shelter'),
        ),
        migrations.AddField(
            model_name='adoptionquestionnaire',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adoption.adoptionapplication'),
        ),
        migrations.AddField(
            model_name='adoptionrecord',
            name='adopter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adoptionrecord',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adoption.adoptionapplication'),
        ),
        migrations.AddField(
            model_name='adoptionrecord',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.cat'),
        ),
        migrations.AddField(
            model_name='adoptionrecord',
            name='shelter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelters.shelter'),
        ),
        migrations.AlterUniqueTogether(
            name='adopterfavorite',
            unique_together={('user', 'cat')},
        ),
    ]
