# Generated by Django 6.0.6 on 2026-07-05 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionquestionnaire',
            name='emergency_contact_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='adoptionquestionnaire',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
